
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3


test:
  <<: *default
  database: db/test.sqlite3

production:
  # adapter: postgresql
  # encoding: Unicode
  database: <%= ENV['DATABASE_URL'] %>
  # host: localhost
  # pool: 5
  # username: postgres
  # password: <%= ENV['Tracker_Password'] %>
